Repository beyond-sw-camp/be06-2nd-4TREES-0909, pull requests merged in 2024-07, with the labels that each got.

#11 [Feat] 입찰 등록 기능 구현 (#1)
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
Labels: BACKEND

#12 [Feat] 공구 등록 기능 엔티티(카테고리, 공구, 관심공구) 개발 (#4)
  project/src/main/java/org/example/fourtreesproject/gpbuy/controller/GpbuyController.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Category.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Groupbuy.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Likes.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/model/request/GpbuyCreateRequest.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/repository/GpbuyRepository.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/service/GpbuyService.java
Labels: BACKEND

#17 [Refactor] 회원Entity, RefreshToken Entity, EmailVerify Entity 수정
  project/src/main/java/org/example/fourtreesproject/config/JwtFilter.java
  project/src/main/java/org/example/fourtreesproject/emailVerify/model/entity/EmailVerify.java
  project/src/main/java/org/example/fourtreesproject/jwt/Repository/RefreshTokenRepository.java
  project/src/main/java/org/example/fourtreesproject/jwt/model/entity/RefreshToken.java
  project/src/main/java/org/example/fourtreesproject/oauth/OAuth2AuthenticationSuccessHandler.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
Labels: BACKEND

#18 [Feat] 상품, 상품이미지, 업체 엔티티 생성
  project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
  project/src/main/java/org/example/fourtreesproject/company/repository/CompanyRepository.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/Product.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
  project/src/main/java/org/example/fourtreesproject/product/repository/ProductImgRepository.java
  project/src/main/java/org/example/fourtreesproject/product/repository/ProductRepository.java
Labels: BACKEND

#19 [Feat] DeliveryAddress Entity 생성 및 User 연관관계 맺기 (#9)
  project/src/main/java/org/example/fourtreesproject/delivery/model/DeliveryAddress.java
  project/src/main/java/org/example/fourtreesproject/delivery/repository/DeliveryAddressRepository.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
Labels: BACKEND

#27 [Style] 공구 패키지 및 클래스 이름 수정 (#26)
  project/.DS_Store
  project/src/main/java/org/example/fourtreesproject/gpbuy/repository/GpbuyRepository.java
  project/src/main/java/org/example/fourtreesproject/gpbuy/service/GpbuyService.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/exception/GroupBuyExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/exception/customs/GroupBuyRegisterFailException.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Category.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Groupbuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/request/GroupBuyCreateRequest.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/CategoryRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/GroupBuyRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#30 [Chore] Swagger config 파일 추가
  project/build.gradle
  project/src/.DS_Store
  project/src/main/.DS_Store
  project/src/main/java/.DS_Store
  project/src/main/java/org/.DS_Store
  project/src/main/java/org/example/.DS_Store
  project/src/main/java/org/example/fourtreesproject/.DS_Store
  project/src/main/java/org/example/fourtreesproject/config/SwaggerConfig.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#32 [Feat] 공구 등록 기능 구현 (#4)
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
Labels: BACKEND

#33 [Feat] 등록된 입찰 조회 구현중 (#31)
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/RegisteredBidListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#34 [Fix] 입찰 엔티티 수정
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
Labels: BACKEND

#36 [Fit] 입찰, 상품 상품이미지 엔티티 수정
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/Product.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
Labels: BACKEND

#35 [Feat] 업체 회원 회원가입 기능 구현
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/exception/InvalidPasswordException.java
  project/src/main/java/org/example/fourtreesproject/user/exception/UserExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
  project/src/main/java/org/example/fourtreesproject/user/model/request/SellerSignupRequest.java
  project/src/main/java/org/example/fourtreesproject/user/repository/SellerDetailRepository.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#37 [Feat] 등록된 입찰 조회 기능 구현 (#31)
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#38 [Feat] 입찰 등록 기능 구현
  project/build.gradle
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/request/BidRegisterRequest.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
Labels: BACKEND

#40 [Fix] 정렬 순서 오류 수정 (#39)
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BUG

#42 [Feat] 업체 정보 등록 기능 구현(#3)
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/request/CompanyRegisterRequest.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
Labels: BACKEND

#48 [Feat] 주문 Entity 개발 완료 (#46)
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
  project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
Labels: BACKEND

#50 [Feat] 쿠폰 등록 기능 구현
  project/src/main/java/org/example/fourtreesproject/coupon/controller/CouponController.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/Coupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/UserCoupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/request/CouponRegisterRequest.java
  project/src/main/java/org/example/fourtreesproject/coupon/repository/CouponRepository.java
  project/src/main/java/org/example/fourtreesproject/coupon/service/CouponService.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
  project/src/main/java/org/example/fourtreesproject/user/model/response/UserInfoResponse.java
Labels: BACKEND

#52 [Feat] 입찰 현황 조회 기능 예외 처리 전 (#5)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/response/BidMyListResponse.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND

#53 [Feat] 공구 전체 조회 기능 구현 (#49)
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/GroupBuyRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
Labels: BACKEND

#51 [Feat] 업체 정보 수정 기능 구현 (#20)
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
  project/src/main/java/org/example/fourtreesproject/company/model/request/CompanyModifyRequest.java
  project/src/main/java/org/example/fourtreesproject/company/repository/CompanyRepository.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
Labels: BACKEND

#54 [Feat] 일반 회원 상세 정보 조회 기능 구현 (#08)
  project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/Coupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/UserCoupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/response/CouponResponse.java
  project/src/main/java/org/example/fourtreesproject/delivery/model/response/DeliveryAddressResponse.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/exception/UserExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/user/exception/custom/InvalidPasswordException.java
  project/src/main/java/org/example/fourtreesproject/user/exception/custom/InvalidUserException.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
  project/src/main/java/org/example/fourtreesproject/user/model/response/UserInfoResponse.java
  project/src/main/java/org/example/fourtreesproject/user/model/response/UserSignupResponse.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#56 [Feat] 업체 정보 조회 기능 구현 (#21)
  project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
  project/src/main/java/org/example/fourtreesproject/company/model/response/CompanyDetailResponse.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
Labels: BACKEND

#59 [Fix] 업체 정보 조회 에러 수정
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
Labels: BACKEND

#61 [Feat] 업체 회원 상세 정보 조회 구현 (#57)
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
  project/src/main/java/org/example/fourtreesproject/user/model/response/SellerInfoResponse.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#62 [Fix] GroupBuy Entity에 컬럼 추가 (#58)
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND, FIX

#65 [Feat] 공구 상세조회 기능 구현 (#63)
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyDetailResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
Labels: BACKEND

#66 [Feat] 입찰 대기 공구 조회 기능 예외 처리 전 (#15)
  project/build.gradle
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/response/GpbuyWaitListResponse.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/GroupBuyRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDsl.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDslImpl.java
Labels: BACKEND

#68 [Feat] 관심 공구 등록/취소 기능 구현
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
Labels: BACKEND

#71 [Feat] 입찰 수정 기능 예외 처리 전 (#13)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
  project/src/main/java/org/example/fourtreesproject/bid/model/request/BidModifyRequest.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND

#72 [Feat] 관심공구 조회기능 구현 (#70)
  project/build.gradle
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/exception/customs/GroupBuyRegisterFailException.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyLikesListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#73 [Feat] 입찰 취소 기능 예외 처리 전 (#14)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
  project/src/main/java/org/example/fourtreesproject/bid/model/request/BidCancelRequest.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND

#75 [Fix] 입찰 수정 조건 변경 (#13)
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND

#76 [Feat] 상품 등록 기능 구현 (#6)
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
  project/src/main/java/org/example/fourtreesproject/config/S3Config.java
  project/src/main/java/org/example/fourtreesproject/file/CloudFileUploadService.java
  project/src/main/java/org/example/fourtreesproject/file/FileUploadService.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Category.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/CategoryRepository.java
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/Product.java
  project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
  project/src/main/java/org/example/fourtreesproject/product/model/request/ProductRegisterRequest.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
Labels: BACKEND

#79 [Fix] 조회 조건 오입력 수정
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDslImpl.java
Labels: BACKEND

#81 [Feat] 주문, 공구 시작, 공구 참여, 입찰 선정 기능 구현
  project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
  project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
  project/src/main/java/org/example/fourtreesproject/config/PortoneConfig.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/Coupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/UserCoupon.java
  project/src/main/java/org/example/fourtreesproject/coupon/repository/UserCouponRepository.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
  project/src/main/java/org/example/fourtreesproject/orders/exception/OrderExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/orders/exception/custom/InvalidOrderException.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
  project/src/main/java/org/example/fourtreesproject/orders/model/request/OrderRequest.java
  project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
  project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
Labels: BACKEND

#84 [Feat] 사업자등록번호 진위확인 기능 구현
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/controller/CompanyRegVerifyController.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/dto/CompanyRegVeriifyDto.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/model/entity/CompanyRegVerify.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/model/request/CompanyRegVerifyRequest.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/model/response/CompanyRegVerifyResponse.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/repository/CompanyRegVerifyRepository.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/service/CompanyRegVerifyService.java
Labels: BACKEND

#86 [Feat] 업체 회원가입 처리 전 사업자등록번호 검증 로직 추가 (#82)
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/controller/CompanyRegVerifyController.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/repository/CompanyRegVerifyRepository.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/service/CompanyRegVerifyService.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/model/request/SellerSignupRequest.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#90 [Refactor]공구 기능의 유저정보를 시큐리티 컨텍스트에서 받아오도록 리팩토링 (#87)
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#89 [Feat] 주문 페이지 조회 기능 구현
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
  project/src/main/java/org/example/fourtreesproject/orders/model/response/OrderPageResponse.java
  project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
  project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
  project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
  project/src/main/java/org/example/fourtreesproject/user/model/response/UserCouponResponse.java
Labels: BACKEND

#85 [Feat] 주문 내역 조회 구현 (#83)
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
  project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
  project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
  project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
Labels: BACKEND

#93 [Feat] 등록 상품 조회 기능 구현 (#25)
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductCategoryResponse.java
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductImgResponse.java
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductMylistResponse.java
  project/src/main/java/org/example/fourtreesproject/product/repository/ProductImgRepository.java
  project/src/main/java/org/example/fourtreesproject/product/repository/ProductRepository.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
Labels: BACKEND

#95 [Refactor] 공구 조회시 종료까지 남은시간 계산해서 응답에 추가 (#92)
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyDetailResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyLikesListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyListResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#96 [Fix] 입찰 기능 예외 처리 (#94)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/exception/BidExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/bid/exception/customs/InvalidBidException.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
  project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
Labels: BACKEND

#100 [Docs] UserController에 swagger 설정 (#99)
  project/src/main/java/org/example/fourtreesproject/coupon/controller/CouponController.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
Labels: DOC

#101 [Docs] OrderController에 swagger 설정 및 swagger config 수정
  project/src/main/java/org/example/fourtreesproject/config/SwaggerConfig.java
  project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
Labels: DOC

#103 [Fix] 일반 회원 정보 상세 조회 시 사용할 수 없는 쿠폰은 조회 안되도록 수정 (#102)
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: FIX

#104 [Fix] 업체기능 권한설정 코드 수정
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/request/CompanyModifyRequest.java
  project/src/main/java/org/example/fourtreesproject/file/CloudFileUploadService.java
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
Labels: BACKEND

#109 [Docs] ProductController swagger 설정 (#99)
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
Labels: DOC

#108 [Docs] CompanyController swagger 설정(#99)
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
Labels: DOC

#112 [Fix] 입찰 기능 추가 예외 처리 (#94)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
Labels: BACKEND, FIX

#115 [Fix] user, user_detail 테이블 연관관계 수정으로 인한 코드수정 (#114)
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: FIX

#116 [fix] swagger 에러
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
Labels: BACKEND

#118 [Fix] 공구 취소 기능 및 전반적인 공구기능 수정 (#117)
  project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
  project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
Labels: FIX

#120 [Refactor] 입찰 현황 조회 성능 개선 완료 (#97)
  project/src/main/java/org/example/fourtreesproject/bid/model/response/BidMyListResponse.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND

#122 [Refactor] 관심 공구 조회 쿼리빈도 개선 (#121)
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
Labels: BACKEND, DB, FIX

#124 [Refactor] global exception으로 변경
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/exception/BidExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
  project/src/main/java/org/example/fourtreesproject/exception/GlobalExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/GroupBuyRegisterFailException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidBidException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidOrderException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidUserException.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/exception/GroupBuyExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/orders/exception/OrderExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/exception/UserExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#126 [Perf] 주문 내역 조회 성능 개선
  project/src/main/java/org/example/fourtreesproject/aop/MethodExecutionTimer.java
  project/src/main/java/org/example/fourtreesproject/common/annotation/Timer.java
  project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
  project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
  project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
  project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
Labels: BACKEND

#129 [Fix] 중복 이메일 회원 가입 불가능 하게 설정
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND, FIX

#131 [Fix] coupon이 없는 일반 회원 정보 조회시 오류 fix (#130)
  project/src/main/java/org/example/fourtreesproject/user/repository/UserRepository.java
Labels: BACKEND, FIX

#133 [Fix] swagger에서 상품이미지를 선택할 수 있도록 설정 추가
  project/src/main/java/org/example/fourtreesproject/config/MultipartJackson2HttpMessageConverter.java
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
Labels: BACKEND, FIX

#134 [Fix] 입찰 대기 공구 조회 swagger 설정 변경 (#132)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
Labels: BACKEND, FIX

#135 [Fix] 상품 조회 버그 수정
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCompanyException.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
Labels: BACKEND, FIX

#137 [Feat] swagger 페이지에 토큰 정보 제공
  project/src/main/java/org/example/fourtreesproject/config/SwaggerConfig.java
Labels: DOC, BACKEND

#139 [Fix] 사업자등록번호 api swagger 설정 변경 (#132)
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/controller/CompanyRegVerifyController.java
Labels: BACKEND, FIX

#140 [Fix] 업체 중복 등록 버그 해결, 예외 처리 버그 해결 (#138)
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
  project/src/main/java/org/example/fourtreesproject/exception/GlobalExceptionHandler.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/GroupBuyRegisterFailException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidBidException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCompanyException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCustomException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidOrderException.java
  project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidUserException.java
Labels: BACKEND, FIX

#142 [Feat] 상품 조회시 productIdx도 같이 반환하도록 수정 (#141)
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductMylistResponse.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
Labels: BACKEND

#143 [Fix] 사업자등록번호 인증 api swagger 설정 변경 및 예외 처리 (#132)
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/controller/CompanyRegVerifyController.java
  project/src/main/java/org/example/fourtreesproject/companyRegVerify/service/CompanyRegVerifyService.java
Labels: BACKEND, FIX

#145 [Feat] 입찰 등록 스웨거 기본값 설정, 안쓰는 api 스웨거에서 삭제 (#144)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
Labels: DOC, BACKEND

#146 [Fix] 입찰 기능 swagger 설정 변경 (#132)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
Labels: BACKEND, FIX

#148 [Fix] swagger 업체 기본값 설정
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
Labels: BACKEND, FIX

#149 [Fix] swagger 상품, 결제 기본값, 코멘트 설정
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
Labels: BACKEND, FIX

#151 [Feat] 공구기능 스웨거 기본값, 코멘트 설정 (#150)
  project/src/main/java/org/example/fourtreesproject/exception/custom/GroupBuyRegisterFailException.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/request/GroupBuySearchRequest.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDslImpl.java
Labels: BACKEND

#152 [Fix] 입찰 등록 조건 수정 및 입찰 취소 예외처리 (#119)
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND, FIX

#155 [Fix] 입찰 현황 조회 페이징 처리 (#119)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/querydsl/BidRepositoryDsl.java
  project/src/main/java/org/example/fourtreesproject/bid/repository/querydsl/BidRepositoryDslImpl.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
Labels: BACKEND, FIX

#158 [Feat] security 접근 권한 설정
  project/src/main/java/org/example/fourtreesproject/common/BaseResponse.java
  project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
  project/src/main/java/org/example/fourtreesproject/config/LoginFilter.java
  project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
  project/src/main/java/org/example/fourtreesproject/exception/CustomAccessDeniedHandler.java
  project/src/main/java/org/example/fourtreesproject/exception/CustomAuthenticationEntryPoint.java
Labels: BACKEND

#159 [Hotfix] 스웨거 접근 안되던 현상 hotfix
  project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
Labels: BACKEND

#163 [Fix] 이미 존재하는 이메일로 소셜 로그인 시 실패 처리
  project/src/main/java/org/example/fourtreesproject/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: BACKEND, FIX

#164 [Refactor] 스웨거에 나오는 토큰 값 application.yml로 이동 (#144)
  project/src/main/java/org/example/fourtreesproject/config/SwaggerConfig.java
Labels: BACKEND, FIX

#166 [Feat] refresh token 적용
  project/src/main/java/org/example/fourtreesproject/config/JwtFilter.java
  project/src/main/java/org/example/fourtreesproject/config/LoginFilter.java
  project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
Labels: BACKEND, FIX

#167 [Fix] 이메일 인증 시, 인증 경로 변경
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND, FIX

#171 [Feat] 배송지 등록, 공구 등록 시 idx값 반환
  project/src/main/java/org/example/fourtreesproject/delivery/model/response/DeliveryAddressRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/request/GroupBuyCreateRequest.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
  project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
  project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
Labels: BACKEND

#172 [Fix] 입찰 등록, 쿠폰 등록 response 수정 (#170)
  project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
  project/src/main/java/org/example/fourtreesproject/bid/model/response/BidRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
  project/src/main/java/org/example/fourtreesproject/coupon/controller/CouponController.java
  project/src/main/java/org/example/fourtreesproject/coupon/model/response/CouponRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/coupon/service/CouponService.java
Labels: BACKEND, FIX

#174 [Feat] 공구 상세 조회시 상품 설명과 가격도 같이 반환하도록 수정
  project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyDetailResponse.java
  project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
Labels: BACKEND

#175 [Fix] 업체 등록 Response 수정
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/response/CompanyRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
Labels: BACKEND, FIX

#173 [Fix] 상품 등록 Response 수정
  project/hs_err_pid14160.log
  project/hs_err_pid19300.log
  project/replay_pid14160.log
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
Labels: BACKEND, FIX

#176 [Feat] Swagger에 login api 추가
  project/src/main/java/org/example/fourtreesproject/user/controller/LoginController.java
  project/src/main/java/org/example/fourtreesproject/user/model/request/LoginRequest.java
Labels: BACKEND

#177 [Feat] 최종 배포
  README.md
  docs/0909-시스템 아키텍처.jpg
  docs/API 명세서.pdf
  docs/ERD.png
  docs/공구 시작 시연.gif
  docs/공구 시작, 공구참여 시퀀스 다이어그램.jpg
  docs/공구 조회 및 등록, 입찰 등록 시퀀스 다이어그램.jpg
  docs/상품 등록 시연.gif
  docs/소프트웨어아키텍처.jpg
  docs/업체 등록 시연.gif
  docs/업체 회원 회원가입 시연.gif
  docs/업체 회원 회원가입 시퀀스 다이어그램.png
  docs/일반 회원 회원가입 시연.gif
  docs/입찰대기공구조회시연.gif
  docs/입찰등록시연.gif
  docs/진행 공구 조회.gif
  project/hs_err_pid14160.log
  project/hs_err_pid19300.log
  project/replay_pid14160.log
  project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
  project/src/main/java/org/example/fourtreesproject/company/model/response/CompanyRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
  project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
  project/src/main/java/org/example/fourtreesproject/product/model/response/ProductRegisterResponse.java
  project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
  project/src/main/java/org/example/fourtreesproject/user/controller/LoginController.java
  project/src/main/java/org/example/fourtreesproject/user/model/request/LoginRequest.java
Labels: BACKEND
